#ifndef INCLUSION_GUARDS_IMD2002_RADARAPI_ENUMS_H
#define INCLUSION_GUARDS_IMD2002_RADARAPI_ENUMS_H


/**************************************************************************************
   serial radar standard enumerators
**************************************************************************************/

typedef enum {
    IMD2002_BAUDRATE_110    = 0,
    IMD2002_BAUDRATE_300       ,
    IMD2002_BAUDRATE_600       ,
    IMD2002_BAUDRATE_1200      ,
    IMD2002_BAUDRATE_2400      ,
    IMD2002_BAUDRATE_4800      ,
    IMD2002_BAUDRATE_9600      ,
    IMD2002_BAUDRATE_19200     ,
    IMD2002_BAUDRATE_38400     ,
    IMD2002_BAUDRATE_57600     ,
    IMD2002_BAUDRATE_115200    ,
    IMD2002_BAUDRATE_256000    ,
    IMD2002_BAUDRATE_512000    ,
    IMD2002_BAUDRATE_230400    ,
    IMD2002_BAUDRATE_1000000
} IMD2002_Baudrate_t;


typedef enum {
    IMD2002_API_ERR_OK                                  = 0x0000,
    IMD2002_API_ERR_FUNCTION_DEPRECATED                 ,
    IMD2002_API_ERR_DLL_NOT_FINISHED                    ,
    IMD2002_API_ERR_HANDLE_NOT_INITIALIZED              ,
    IMD2002_API_ERR_COMPORT_DOESNT_EXIST                ,
    IMD2002_API_ERR_COMPORT_CANT_INITIALIZE             ,
    IMD2002_API_ERR_COMPORT_ACCESS_DENIED               ,
    IMD2002_API_ERR_COMPORT_BAUDRATE_NOT_VALID          ,
    IMD2002_API_ERR_COMPORT_CANT_OPEN                   ,
    IMD2002_API_ERR_COMPORT_CANT_SET_FLOW_CONTROL       ,
    IMD2002_API_ERR_COMPORT_CANT_SET_PARITY             ,
    IMD2002_API_ERR_COMPORT_CANT_SET_STOP_BITS          ,
    IMD2002_API_ERR_COMPORT_CANT_SET_DATA_BITS          ,
    IMD2002_API_ERR_COMPORT_CANT_SET_BAUDRATE           ,
    IMD2002_API_ERR_COMPORT_ALREADY_INITIALIZED         ,
    IMD2002_API_ERR_COMPORT_EQUALS_NULL                 ,
    IMD2002_API_ERR_COMPORT_NOT_OPEN                    ,
    IMD2002_API_ERR_COMPORT_NOT_READABLE                ,
    IMD2002_API_ERR_COMPORT_NOT_WRITEABLE               ,
    IMD2002_API_ERR_COMPORT_CANT_WRITE                  ,
    IMD2002_API_ERR_COMPORT_CANT_READ                   ,
    IMD2002_API_ERR_COMMAND_NOT_WRITTEN                 ,
    IMD2002_API_ERR_COMMAND_NOT_READ                    ,
    IMD2002_API_ERR_COMMAND_NO_DATA_RECEIVED            ,
    IMD2002_API_ERR_COMMAND_NO_VALID_FRAME_FOUND        ,
    IMD2002_API_ERR_COMMAND_RX_FRAME_DAMAGED            ,
    IMD2002_API_ERR_COMMAND_FAILURE                     ,
    IMD2002_API_ERR_UNDEFINED_READ                      ,
    IMD2002_API_ERR_COMPORT_LESS_DATA_READ              ,
    IMD2002_API_ERR_COMPORT_SYSTEM_INIT_FAILED          ,
    IMD2002_API_ERR_COMPORT_SYSTEM_ALREADY_INITIALIZED  ,
    IMD2002_API_ERR_COMMAND_RX_FRAME_LENGTH             ,
    IMD2002_API_ERR_COMMAND_MAX_DATA_OVERFLOW           ,
    IMD2002_API_ERR_COMMAND_MAX_IQPAIRS_OVERFLOW        ,
    IMD2002_API_ERR_COMMAND_NOT_ACCEPTED                ,
    IMD2002_API_ERR_NULL_POINTER                        ,
    IMD2002_API_ERR_PARAMETER_OUT_OF_RANGE              ,
    IMD2002_API_ERR_COMMAND_UNEXPECTED_FRAMETYPE        ,
    IMD2002_API_ERR_COMMAND_WITH_FAILURE_CODE
} IMD2002_Result_t;


#endif /* INCLUSION_GUARDS_IMD2002_RADARAPI_ENUMS_H */
